services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  fastapi:
    container_name: FastAPI
    restart: always
    build: ./FastAPI/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    develop:
      watch:
        - action: sync
          path: ./FastAPI/app
          target: /restfulapi/app
        - action: rebuild
          path: ./FastAPI/requirements.txt
    depends_on:
      - mysql
    networks:
      - backend

  ngnix:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/ssl/certs:/etc/ssl/certs
      - ./nginx/ssl/private:/etc/ssl/private
      - ./nginx/logs:/var/log/nginx
    environment:
      SERVER_NAME: ${SERVER_NAME}
    depends_on:
      - fastapi
    networks:
      - backend
  
networks:
  backend:
    driver: bridge

volumes:
  db_data:
